services:
  - type: web
    name: chess-server
    runtime: node
    rootDir: server
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: CLIENT_ORIGIN
        value: https://client-olive-kappa.vercel.app
